version: '3.8'

services:
  frontend:
    image: dakshsawhneyy/discover_dollar_frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on: 
      - backend
    networks:
      - crud_app
  backend:
    image: dakshsawhneyy/discover_dollar_backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/dd_db
    networks:
      - crud_app
  mongo:
    image: mongo:latest
    container_name: mongo
    ports: 
      - "27017:27017"
    networks:
      - crud_app
    volumes:
      - mongo-data:/data/db

networks:
  crud_app:
volumes:
  mongo-data: